-
  name: Code Carpentry Website
  description: The website for the program. Infact, it is this website. This is too meta. On this site we will show off all the projects and code produced by Etsy and Columbia's ADI group.
  user: Etsy-ADI-CodeCarpentry
  repo: CodeCarpentryWebsite
  live_url: http://codecarpentry.herokuapp.com